name: Deploy Octane Image
env:
  BRANCH_NAME: ${{ github.base_ref || github.ref_name }}
  DOCKER_USERNAME: ${{ github.repository_owner }}
  IMAGE_NAME: octane
  TAG: ${{ env.BRANCH_NAME == 'main' && 'latest' || env.BRANCH_NAME }}
on:
  push:
    branches: [ main, swoole, franken ]
jobs:
  deploy_prod:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          context: src
          push: true
